### ISSUE TITLE
Gettin 'deprecated' notice.

### ISSUE THREAD

**Issue by prcoy** [qrbys/atom-theme-marronlatte#1]
Installed in v1.5 (I think) and got a 'deprecated' notice. It is complaining about shadows:. Apparently shadows were removed in 1.3. Thats all I know.

I do like this theme a lot.

**Comment by howyi** [comment]
This notice fix on v0.4.0! https://github.com/qrbys/atom-theme-marronlatte/commit/9c08da8f633a6ce24c35c6b0620ba20e74ae8ddf
thank you for use and file an issue report 🙇
